FROM flink:1.19

RUN curl -fL -o /opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.19.jar \
    https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.3.0-1.19/flink-sql-connector-kafka-3.3.0-1.19.jar

RUN curl -fL -o /opt/flink/lib/flink-sql-avro-confluent-registry-1.19.0.jar \
    https://repo1.maven.org/maven2/org/apache/flink/flink-sql-avro-confluent-registry/1.19.0/flink-sql-avro-confluent-registry-1.19.0.jar